#!/bin/bash
set -e

DIR="$1"

if [ "$DIR" == "" ]; then
  echo "Error: provide project directory"
  exit 1
fi

shift;

cd "$DIR/build" || exit

OUT="../bin/tmp-build"
go build -trimpath -o "$OUT" ./cmd
exec "$OUT" "$@"
