#!/bin/bash
set -e

DIR="$1"

if [ "$DIR" == "" ]; then
  echo "Error: provide project directory"
  exit 1
fi

shift;

cd "$DIR/build" || exit

VERSION=$(git rev-parse --short HEAD)
BUILD_BIN="$DIR/bin/.cache/build-$VERSION"

if [ ! -f "$BUILD_BIN" ]; then
  rm -f ../bin/.cache/build-*

  go build -trimpath -o "$BUILD_BIN" ./cmd
fi

exec "$BUILD_BIN" "$@"
